### PR TITLE
added macOS support

### PR DESCRIPTION
**Pull request by suntrix**
### Checklist

- [x] All new jobs, commands, executors, parameters have descriptions
- [x] Examples have been added for any significant new features
- [x] README has been updated, if necessary

### Motivation, issues

macOS execution environment support is missing. It's very useful to be able to have Android SDK installed there when you're developing mobile app that uses Kotlin Multiplatform (https://kotlinlang.org/docs/multiplatform.html).

### Description

Adds macOS execution environment support to be able to install Android SDK on it.

### CODE REVIEW

**Comment by felicianotech** [comment]
under review

**Comment by ryanbourdais** [comment]
Hi @suntrix, we currently do not support the macOS environment with this orb because it is designed to be used with the tooling provided in the android image and executor. Is there a reason you would like to run both your iOS and android jobs using the android image and orb instead of running the android workflows on the android orb and image while running iOS on the macOS image in parallel, which should be both faster and cheaper?

**Comment by andrzej-hanusek-tg** [comment]
> 

Android executor doesn't support IP ranges. It is a big issue for us because now it's not possible to run e2e with environment working on private VPN.

**Comment by ryanbourdais** [comment]
@andrzej-hanusek-tg have you tried using [the IP Range feature](https://circleci.com/docs/ip-ranges/) in your pipelines?

**Comment by andrzej-hanusek-tg** [comment]
> @andrzej-hanusek-tg have you tried using [the IP Range feature](https://circleci.com/docs/ip-ranges/) in your pipelines?

As I wrote above: IP range feature doesn't work for Android executor. On the other hand, on docker executor doesn't work nested virtualization, so I cannot run emulator.

**Comment by BytesGuy** [comment]
Thank you for the contribution @suntrix, we appreciate it! 

However, this is likely not something we will be officially supporting for a few reasons.

Installing the Android tooling in macOS jobs generally takes a fair chunk of time and therefore costs more build credits. For this reason it is more efficient price wise to use the dedicated Android Docker and VM images that we provide for building and testing Android apps respectively.

Testing in the Android emulator within macOS executors is has never been officially supported as it relies on nested virtualisation. It may work, but we cannot guarantee it - this will continue to be the case with the new M1 platform.

We recommend splitting multi-platform build and tests into dedicated jobs, this way you can take advantage of specific executors/images that play to the advantages of each toolchain and also run builds in parallel which will save you time.

We will close this out for now, but please do feel free to open additional PRs for new features that you might find useful! Thank you 🙂

**Pull request closed without merging**
