### PR TITLE
Fix NDK path

### LINKED ISSUE #2: Unable to use ANDROID_NDK_HOME
### Orb version

0.1.0

### What happened

After running `android/install-ndk`, `ANDROID_NDK_HOME` is empty. It seems like it's not correctly exported. 

### Expected behavior

It should be set to the NDK path.

### PR DESCRIPTION
**Pull request by guillaume-tgl**
Export variable so that it can be used in other steps.

Fix #2

### Checklist

- [ ] All new jobs, commands, executors, parameters have descriptions
- [ ] Examples have been added for any significant new features
- [ ] README has been updated, if necessary

### Motivation, issues

Fix #2

### CODE REVIEW

**Comment by iynere** [comment]
@guillaume-tgl i'm not sure this will 100% fix the issue, but it will definitely help, so i'm happy to merge it

**Comment by guillaume-tgl** [comment]
@iynere why do you think it's not going to solve the issue?

**Comment by iynere** [comment]
@guillaume-tgl because CircleCI steps don't source `.bashenv` by default, i dont think

**Comment by guillaume-tgl** [comment]
[This page](https://circleci.com/docs/2.0/env-vars/#using-bash_env-to-set-environment-variables) seems to indicate the opposite:
> In every step, CircleCI uses bash to source BASH_ENV. This means that BASH_ENV is automatically loaded and run, allowing you to use interpolation and share environment variables across run steps.

And it fixed the issue in my project :)

**Comment by iynere** [comment]
ah, so it does 😄 good find lol, that's actually very helpful for myself to know

there's still an edge case here, as not _every_ docker image _has_ bash—e.g., many alpine images don't—but i believe this orb doesn't support alpine yet anyway, so it's a moot point (but one we should address at some point)

**Pull request merged**
