### PR TITLE
[semver:minor] Add parameter resource-class for android docker executor

### PR DESCRIPTION
**Pull request by tadashi0713**
As same as Android Machine executor, I added `resource-class` parameter for Docker Executor 

### Checklist

- [x] All new jobs, commands, executors, parameters have descriptions
- [x] Examples have been added for any significant new features
- [x] README has been updated, if necessary

### CODE REVIEW

**Review by KyleTryon — CHANGES_REQUESTED** [review]
Request: Add this new parameter to each of this orb's jobs so that the value may be passed through the job to the executor

**Review by KyleTryon — CHANGES_REQUESTED** [review]
Add the resource class parameter to both jobs.

Note: you want to add the exact same `resource-class` parameter to both jobs with the same definition you used in the executor. You then pass that value to the executor.

This lets people specify the resource class of a job with a parameter. 
https://circleci.com/docs/2.0/orbs-best-practices/#consider-pass-through-parameters

**Comment by felicianotech** [comment]
This is already done in an open PR that will get merged this week.

**Comment by felicianotech** [comment]
Actually, not this exactly but we likely want to combine the two. Let's not merge this just yet.

**Review by felicianotech — APPROVED** [review]
This looks good. I'm going to merge this though without releasing just yet so I can add it to the major release that will be coming out this week.

Thanks.

**Pull request merged**
